const seedDays=[['2026-09-11',1247,339.4],['2026-09-12',817,338.4],['2026-09-13',1268,337.4],['2026-09-14',952,335.8],['2026-09-15',817,334.6],['2026-09-16',832,335.2],['2026-09-17',1060,334],['2026-09-18',1062,334.4],['2026-09-19',1660,null],['2026-09-20',760,null],['2026-09-21',711,335],['2026-09-22',1150,null],['2026-09-23',840,null],['2026-09-24',1015,null],['2026-09-25',985,null],['2026-09-26',1486,null],['2026-09-27',985,334.8],['2026-09-28',985,null]];
const key='food-weight-tracker-v1';
const foodLookupUrl=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'/api/food-lookup':'https://www.folkbandura.com/private/food-tracker-food-lookup.php';
const localDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const today=localDate(new Date());
const defaultNutrients={'2026-09-13':{'Vitamin A':118,'Vitamin C':128,'Vitamin D':104,'Iron':112,'Calcium':59,'Magnesium':61,'Potassium':38,'Zinc':112},'2026-09-14':{'Vitamin A':125,'Vitamin C':140,'Vitamin D':104,'Iron':115,'Calcium':75,'Magnesium':70,'Potassium':50,'Zinc':100}};
let state=JSON.parse(localStorage.getItem(key)||'null')||{days:Object.fromEntries(seedDays.map(([date,calories,weight])=>[date,{calories,weight}])),foods:window.importedFoods||[],nutrients:defaultNutrients,historyImportVersion:2};
if(!state.historyImportVersion){state.foods=[...(window.importedFoods||[]),...(state.foods||[])];state.historyImportVersion=1}
if(state.historyImportVersion<2){const moved=state.foods.filter(food=>food.date==='2026-09-27').slice(-9);moved.forEach(food=>food.date='2026-09-28');for(const date of ['2026-09-27','2026-09-28']){const intake=state.foods.filter(food=>food.date===date).reduce((sum,food)=>sum+food.calories,0);if(intake||state.days[date])getDay(date).calories=intake}state.historyImportVersion=2}
let charts={}; const $=s=>document.querySelector(s); const save=()=>{localStorage.setItem(key,JSON.stringify(state));window.dispatchEvent(new CustomEvent('food-tracker-state-saved'))}; const dates=()=>Object.keys(state.days).sort(); const label=d=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
function getDay(date){return state.days[date]||(state.days[date]={calories:0,weight:null})} function download(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function chart(id,config){charts[id]?.destroy();charts[id]=new Chart($('#'+id),config)}
function common(title){return {responsive:true,maintainAspectRatio:true,plugins:{legend:{position:'bottom'},title:{display:false,text:title},zoom:{pan:{enabled:true,mode:'x'},zoom:{wheel:{enabled:true},pinch:{enabled:true},mode:'x'}}},interaction:{intersect:false,mode:'index'}}}
function render(){save(); const foodCalories=state.foods.reduce((totals,food)=>{const calories=Number(food.calories);if(food.date&&Number.isFinite(calories))totals[food.date]=(totals[food.date]||0)+calories;return totals},{}), caloriesFor=date=>(foodCalories[date]??Number(getDay(date).calories))||0, ds=[...new Set([...dates(),...Object.keys(foodCalories)])].sort(), latest=[...ds].reverse().find(d=>state.days[d]?.weight!=null), weights=ds.filter(d=>state.days[d]?.weight!=null); $('#todayLabel').textContent=label(today); $('#todaySummary').textContent=`${state.foods.filter(f=>f.date===today).length} food item(s) logged today`;
 $('#latestWeight').textContent=latest?`${state.days[latest].weight} lb`:'—'; $('#weightChange').textContent=weights.length>1?`${(state.days[weights.at(-1)].weight-state.days[weights.at(-2)].weight).toFixed(1)} lb since prior entry`:'No prior weight logged'; $('#todayCalories').textContent=Math.round(caloriesFor(today)).toLocaleString(); let last7=ds.slice(-7).map(caloriesFor).filter(Boolean);$('#calAverage').textContent=last7.length?`${Math.round(last7.reduce((a,b)=>a+b,0)/last7.length)} kcal`:'—';
 chart('weightChart',{type:'line',data:{labels:weights.map(label),datasets:[{label:'Weight (lb)',data:weights.map(d=>state.days[d].weight),borderColor:'#1a6b51',backgroundColor:'#1a6b5122',fill:true,tension:.25,pointRadius:4}]},options:{...common('Weight'),scales:{y:{title:{display:true,text:'lb'}}}}});
 chart('calorieChart',{type:'line',data:{labels:ds.map(label),datasets:[{label:'Calories',data:ds.map(caloriesFor),borderColor:'#c96d3b',backgroundColor:'#c96d3b22',fill:true,tension:.25,pointRadius:4}]},options:{...common('Calories'),scales:{y:{beginAtZero:true,title:{display:true,text:'kcal'}}}}});
 const nutrients=[...new Set(Object.values(state.nutrients).flatMap(Object.keys))], colors=['#1a6b51','#c96d3b','#3878a8','#9b5d9b','#b29a1c','#d04e60','#5c7d35','#456b9c'];const nd=Object.keys(state.nutrients).sort();chart('nutrientChart',{type:'line',data:{labels:nd.map(label),datasets:nutrients.map((n,i)=>({label:n,data:nd.map(d=>state.nutrients[d][n]??null),borderColor:colors[i%colors.length],tension:.2,spanGaps:true}))},options:{...common('%DV'),scales:{y:{beginAtZero:true,title:{display:true,text:'% daily value'},grid:{color:c=>c.tick.value===100?'#1a6b5188':'#e7e9e3'}}}}});
 const grouped=Object.entries(state.foods.reduce((all,food,index)=>{(all[food.date]??=[]).push({...food,index});return all},{})).sort(([a],[b])=>b.localeCompare(a));
 $('#foodTable').innerHTML=grouped.map(([date,foods])=>{const calories=foods.reduce((sum,food)=>sum+food.calories,0);return `<tr class="date-group"><td colspan="6"><details><summary><strong>${label(date)}</strong><span>${foods.length} item${foods.length===1?'':'s'} · ${calories.toLocaleString()} kcal</span></summary><div class="food-items">${foods.map(f=>`<div class="food-item"><span>${f.meal}</span><span>${f.name}</span><span>${f.serving}</span><span>${f.calories} kcal</span><button data-remove-index="${f.index}" aria-label="Remove ${f.name}">Remove</button></div>`).join('')}</div></details></td></tr>`}).join('')||'<tr><td colspan="6" class="muted">New foods you add will appear here. Historical calorie totals were imported from the workbook.</td></tr>';
}
$('#weightForm').addEventListener('submit',e=>{e.preventDefault();getDay(today).weight=Number($('#weightInput').value);$('#weightInput').value='';render()});
function splitFoodText(text){const mealPattern=/(?:for\s+)?(breakfast|lunch|dinner|late snack|snack|supplement)s?\s*(?:i\s+(?:had|ate)|was|:)?\s*/gi;const matches=[...text.matchAll(mealPattern)];const entries=[];const addFoods=(meal,words)=>words.replace(/^(?:then\s+)?/i,'').split(/\s*(?:,|&|\+)\s*|\s+and\s+(?=(?:a |an |some |\d))/i).map(name=>name.replace(/^(?:i\s+(?:had|ate)\s+)?(?:a|an|some)\s+/i,'').trim()).filter(name=>name.length>1).forEach(name=>entries.push({meal,name}));if(matches.length){matches.forEach((match,index)=>addFoods(match[1].replace(/\b\w/g,c=>c.toUpperCase()),text.slice(match.index+match[0].length,matches[index+1]?.index).trim().replace(/[.;]+$/,'')))}else addFoods('Snack',text.trim().replace(/[.;]+$/,''));return entries}
async function lookupFood(query){const res=await fetch(foodLookupUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({food:query})}),text=await res.text();let result;try{result=JSON.parse(text)}catch{throw new Error('Food lookup service returned an unreadable response.')}if(!res.ok)throw new Error(result.error||'Food lookup failed');return result}
$('#foodNarrative').addEventListener('submit',async e=>{e.preventDefault();const items=splitFoodText($('#foodText').value);if(!items.length){$('#searchStatus').textContent='Tell me what you ate, for example: “Breakfast: eggs, toast.”';return}$('#searchStatus').textContent=`Searching the food database for ${items.length} item(s)…`;$('#searchResults').innerHTML='';const results=[];for(const [index,item] of items.entries()){try{$('#searchStatus').textContent=`Searching ${index+1} of ${items.length}: ${item.name}…`;results.push({item,found:await lookupFood(item.name)})}catch(error){results.push({item,error})}}const saved=[];results.forEach(({item,found,error})=>{if(error)return;const food={date:today,meal:item.meal,name:item.name,serving:found.serving,calories:found.calories};state.foods.push(food);getDay(today).calories+=food.calories;saved.push({...food,matchedName:found.matchedName})});$('#foodText').value='';const failed=results.filter(result=>result.error);$('#searchStatus').textContent=`Added ${saved.length} of ${items.length} item(s).${failed.length?' The unmatched items were not added—try a more specific name or brand.':''}`;$('#searchResults').innerHTML=results.map(({item,found,error})=>error?`<div class="result"><span><strong>${item.meal}: ${item.name}</strong><br><small>Not added: ${error.message||'food lookup failed'}</small></span></div>`:`<div class="result"><span><strong>${item.meal}: ${item.name}</strong><br><small>${found.serving} · ${found.calories} kcal estimate${found.matchedName.toLowerCase()!==item.name.toLowerCase()?` · matched: ${found.matchedName}`:''}</small></span></div>`).join('');render()});
$('#toggleNutrients').onclick=()=>$('#nutrientForm').classList.toggle('hidden');$('#nutrientDate').value=today;
$('#nutrientForm').addEventListener('submit',e=>{e.preventDefault();let d=$('#nutrientDate').value;state.nutrients[d]??={};state.nutrients[d][$('#nutrientName').value]=Number($('#nutrientValue').value);e.target.reset();$('#nutrientDate').value=today;render()});
$('#foodTable').addEventListener('click',e=>{let i=e.target.dataset.removeIndex;if(i===undefined)return;let f=state.foods[Number(i)];getDay(f.date).calories=Math.max(0,getDay(f.date).calories-f.calories);state.foods.splice(Number(i),1);render()});
$('#exportData').onclick=()=>download('food-weight-tracker.json','application/json',JSON.stringify(state,null,2));$('#exportCsv').onclick=()=>download('food-log.csv','text/csv',['date,meal,food,serving,calories',...state.foods.map(f=>[f.date,f.meal,f.name,f.serving,f.calories].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n'));
$('#importData').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let text=await f.text();if(f.name.endsWith('.json'))state=JSON.parse(text);else{let rows=text.trim().split(/\r?\n/).slice(1).map(r=>r.match(/("(?:[^"]|"")*"|[^,])+/g)?.map(x=>x.replace(/^"|"$/g,'').replaceAll('""','"')));rows.filter(Boolean).forEach(([date,meal,name,serving,calories])=>{let item={date,meal,name,serving,calories:Number(calories)};state.foods.push(item);getDay(date).calories+=item.calories})}render()}catch{alert('Could not import that file. Use a tracker JSON export or a CSV with date, meal, food, serving, calories.')}};
let popupChart;
function popupScales(id){if(id==='weightChart')return {y:{title:{display:true,text:'lb'}}};if(id==='calorieChart')return {y:{beginAtZero:true,title:{display:true,text:'kcal'}}};return {y:{beginAtZero:true,title:{display:true,text:'% daily value'},grid:{color:'#e7e9e3'}}}}
document.querySelectorAll('.popout').forEach(b=>b.onclick=()=>{let source=charts[b.dataset.chart],d=$('#chartDialog');$('#dialogTitle').textContent=b.dataset.chart==='nutrientChart'?'Vitamins & nutrients':source.data.datasets[0]?.label||'Chart';d.showModal();popupChart?.destroy();requestAnimationFrame(()=>{popupChart=new Chart($('#dialogChart'),{type:source.config.type,data:JSON.parse(JSON.stringify(source.data)),options:{...common(''),scales:popupScales(b.dataset.chart)}});popupChart.resize()})});$('#closeDialog').onclick=()=>{$('#chartDialog').close();popupChart?.destroy();popupChart=null};render();
