const vaultStorageKey='food-weight-tracker-v1';
const vaultStatus=document.querySelector('#vaultStatus');
const toBase64=bytes=>btoa(String.fromCharCode(...bytes));
const fromBase64=text=>Uint8Array.from(atob(text),char=>char.charCodeAt(0));
async function vaultKey(passphrase,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function downloadVault(contents){const link=document.createElement('a'),url=URL.createObjectURL(new Blob([contents],{type:'application/json'}));link.href=url;link.download='food-tracker-vault.enc';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
document.querySelector('#createVault').addEventListener('click',async()=>{const passphrase=document.querySelector('#vaultPassphrase').value;const data=localStorage.getItem(vaultStorageKey);if(passphrase.length<6){vaultStatus.textContent='Use a passphrase of at least 6 characters.';return}if(!data){vaultStatus.textContent='There is no tracker data to encrypt yet.';return}try{const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await vaultKey(passphrase,salt),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(data));downloadVault(JSON.stringify({version:1,kdf:'PBKDF2-SHA-256',iterations:250000,salt:toBase64(salt),iv:toBase64(iv),ciphertext:toBase64(new Uint8Array(ciphertext))}));vaultStatus.textContent='Encrypted vault downloaded. Store it somewhere private, then upload that .enc file to your domain when ready.';document.querySelector('#vaultPassphrase').value=''}catch{vaultStatus.textContent='Could not create the encrypted vault. Please try again.'}});
document.querySelector('#restoreVault').addEventListener('click',async()=>{const passphrase=document.querySelector('#vaultPassphrase').value,file=document.querySelector('#vaultFile').files[0];if(!file||!passphrase){vaultStatus.textContent='Choose a vault file and enter its passphrase.';return}try{const vault=JSON.parse(await file.text());if(vault.version!==1)throw new Error();const key=await vaultKey(passphrase,fromBase64(vault.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(vault.iv)},key,fromBase64(vault.ciphertext));const state=JSON.parse(new TextDecoder().decode(plain));if(!state.days||!Array.isArray(state.foods))throw new Error();localStorage.setItem(vaultStorageKey,JSON.stringify(state));location.reload()}catch{vaultStatus.textContent='Could not unlock that vault. Check the passphrase and file, then try again.'}});
async function restoreVaultText(text,passphrase){const vault=JSON.parse(text);if(vault.version!==1)throw new Error();const key=await vaultKey(passphrase,fromBase64(vault.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(vault.iv)},key,fromBase64(vault.ciphertext));const state=JSON.parse(new TextDecoder().decode(plain));if(!state.days||!Array.isArray(state.foods))throw new Error();localStorage.setItem(vaultStorageKey,JSON.stringify(state));location.reload()}
document.querySelector('#restoreHostedVault').addEventListener('click',async()=>{const passphrase=document.querySelector('#vaultPassphrase').value;if(!passphrase){vaultStatus.textContent='Enter your vault passphrase first.';return}vaultStatus.textContent='Downloading encrypted vault…';try{const response=await fetch('/api/hosted-vault'),result=await response.json();if(!response.ok)throw new Error();await restoreVaultText(result.vault,passphrase)}catch{vaultStatus.textContent='Could not unlock the hosted vault. Check the passphrase and try again.'}});
